# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Diary' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Diary
  pod 'omiroshn2019', :git => 'https://github.com/omiroshn/omiroshn2019.git'
end
