# Uncomment the next line to define a global platform for your project
#platform :ios, '11.2'

target 'WeatherForecast' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherForecast
  pod "DarkSkyKit"
  pod 'RecastAI','~>3.5.0'
  pod 'MessageKit','~>1.0'

end
